Drop support for 8.0, add testing for 8.4 (#28)
* Upgrading to PHP 8.1

* Fixing tests

* Dont fail fast

* Drop comment

* Fixing phpcs

* Rename class methods for PSR

* Swap sprintf for direct variable

* Editor config

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,10 +6,10 @@ jobs:
   test:
     runs-on: ${{ matrix.os }}
     strategy:
-      fail-fast: true
+      fail-fast: false
       matrix:
-        os: [ubuntu-latest]
-        php: [7.4, 8.0, 8.1]
+        os: [ubuntu-latest, windows-latest, macos-latest]
+        php: [8.1, 8.2, 8.3, 8.4]
         stability: [prefer-lowest, prefer-stable]
 
     name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}
@@ -33,5 +33,33 @@ jobs:
       - name: Install dependencies
         run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction
 
-      - name: Execute tests
-        run: composer run test
+      - name: Composer Validate
+        run: composer validate --strict
+
+      - name: Execute phpcs
+        if: matrix.os == 'ubuntu-latest'
+        run: composer run phpcs
+
+      - name: Execute phpunit
+        run: composer run phpunit
+
+  # This required job ensures that all PR checks have passed before merging.
+  all-pr-checks-passed:
+    name: All PR checks passed
+    needs:
+      - test
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check job statuses
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
+            echo "One or more jobs failed"
+            exit 1
+          elif [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more jobs were cancelled"
+            exit 1
+          else
+            echo "All jobs passed or were skipped"
+            exit 0
+          fi
